### PR TITLE
Use classes from data-harmonizer package

### PR DESCRIPTION
**Pull request by pkalita-lbl**
These changes bring in `data-harmonizer` as a package with importable classes. It replaces the JavaScript files from `sheets_and_friends` that were being included via script tags and all the global variables required with those.

You can try these changes if you have this branch locally: https://github.com/pkalita-lbl/DataHarmonizer/tree/issue-312. There is a [PR](https://github.com/cidgoh/DataHarmonizer/pull/329) in `DataHarmonizer` for those changes. Once that's accepted I'll publish the `data-harmonizer` package to NPM and update the `package.json` file here. Until then this is just a draft to look at.

### CODE REVIEW

**Review by subdavis — COMMENTED** [review]
I endorse all the suggested changes here.  Once the DataHarmonizer package is published and this PR is updated, someone at Kitware should go through a test of the existing functionality and accept this.

**Comment by pkalita-lbl** [comment]
@mcovalt these changes are ready for review now

**Comment by pkalita-lbl** [comment]
Hi @mcovalt -- @turbomam and I were hoping to do some reorganizing of the `sheets_and_friends` repo, but we can't do it with the way that this project currently relying on `sheets_and_friends` (i.e. what this PR is addressing, in part). Is there a timeline for merging this PR?

**Comment by ssarrafan** [comment]
Adding to next sprint per @jeffbaumes

**Review by mcovalt — APPROVED** [review]

**Pull request merged**
