### PR TITLE
Add funding source box to study form

### PR DESCRIPTION
**Pull request by JamesTessmer**
This PR is related to issue: https://github.com/microbiomedata/issues/issues/229 and is 1 of 2 PRs needed to complete the issue.

This PR adds the `funding_sources` field to the study form schema and supports it by adding a `funding_sources` text box on the study form page in the submission portal. It also adds necessary connections to the rest of the schema to propagate information entered in the text box.

### CODE REVIEW

**Comment by JamesTessmer** [comment]
@pkalita-lbl it looks like all the `types-pkg-resources` versions were yanked on pypi https://pypi.org/project/types-pkg-resources/#history
It directs users to setuptools now. Should we make a small PR to update that dependency?

**Comment by pkalita-lbl** [comment]
> Should we make a small PR to update that dependency?

Yes I will open one shortly. Once that's merged into `main` it can be merged into this branch.

**Comment by JamesTessmer** [comment]
@pkalita-lbl Merged the fix with main into this PR so now everything passes and it should be ready for review.

**Review by pkalita-lbl — CHANGES_REQUESTED** [review]
When I run these changes locally, the existing submission records residing in my local database cannot be served through the `/api/metadata_submission` endpoint. The backend exception is related to a missing `funding_sources` field on the existing records:

```
backend-1  | INFO:     192.168.65.1:61320 - "GET /api/metadata_submission?limit=10&offset=0 HTTP/1.1" 500 Internal Server Error
backend-1  | ERROR:    Exception in ASGI application
backend-1  | Traceback (most recent call last):
backend-1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
backend-1  |     result = await app(  # type: ignore[func-returns-value]
backend-1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend-1  |     return await self.app(scope, receive, send)
backend-1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
backend-1  |     await super().__call__(scope, receive, send)
backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
backend-1  |     await self.middleware_stack(scope, receive, send)
backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
backend-1  |     raise exc
backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
backend-1  |     await self.app(scope, receive, _send)
backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
backend-1  |     await self.app(scope, receive, send)
backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/sessions.py", line 77, in __call__
backend-1  |     await self.app(scope, receive, send_wrapper)
backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
backend-1  |     raise exc
backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
backend-1  |     await self.app(scope, receive, sender)
backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
backend-1  |     await route.handle(scope, receive, send)
backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
backend-1  |     await self.app(scope, receive, send)
backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
backend-1  |     response = await func(request)
backend-1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 234, in app
backend-1  |     response_data = await serialize_response(
backend-1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 137, in serialize_response
backend-1  |     raise ValidationError(errors, field.type_)
backend-1  | pydantic.error_wrappers.ValidationError: 10 validation errors for MetadataSubmissionResponse
backend-1  | response -> results -> 0 -> metadata_submission -> studyForm -> funding_sources
backend-1  |   field required (type=value_error.missing)
backend-1  | response -> results -> 1 -> metadata_submission -> studyForm -> funding_sources
backend-1  |   field required (type=value_error.missing)
backend-1  | response -> results -> 2 -> metadata_submission -> studyForm -> funding_sources
backend-1  |   field required (type=value_error.missing)
backend-1  | response -> results -> 3 -> metadata_submission -> studyForm -> funding_sources
backend-1  |   field required (type=value_error.missing)
backend-1  | response -> results -> 4 -> metadata_submission -> studyForm -> funding_sources
backend-1  |   field required (type=value_error.missing)
backend-1  | response -> results -> 5 -> metadata_submission -> studyForm -> funding_sources
backend-1  |   field required (type=value_error.missing)
backend-1  | response -> results -> 6 -> metadata_submission -> studyForm -> funding_sources
backend-1  |   field required (type=value_error.missing)
backend-1  | response -> results -> 7 -> metadata_submission -> studyForm -> funding_sources
backend-1  |   field required (type=value_error.missing)
backend-1  | response -> results -> 8 -> metadata_submission -> studyForm -> funding_sources
backend-1  |   field required (type=value_error.missing)
backend-1  | response -> results -> 9 -> metadata_submission -> studyForm -> funding_sources
backend-1  |   field required (type=value_error.missing)
```

I think possible paths forward are:

* Type `funding_sources` as an `Optional[str]` in StudyForm
* Create a [new migration](https://github.com/microbiomedata/nmdc-server/blob/main/docs/development.md#generating-new-migrations) to back-populate the `funding_sources` field set to an empty string in existing submissions.

**Comment by JamesTessmer** [comment]
> When I run these changes locally, the existing submission records residing in my local database cannot be served through the `/api/metadata_submission` endpoint. The backend exception is related to a missing `funding_sources` field on the existing records:
> 
> ```
> backend-1  | INFO:     192.168.65.1:61320 - "GET /api/metadata_submission?limit=10&offset=0 HTTP/1.1" 500 Internal Server Error
> backend-1  | ERROR:    Exception in ASGI application
> backend-1  | Traceback (most recent call last):
> backend-1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
> backend-1  |     result = await app(  # type: ignore[func-returns-value]
> backend-1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
> backend-1  |     return await self.app(scope, receive, send)
> backend-1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
> backend-1  |     await super().__call__(scope, receive, send)
> backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
> backend-1  |     await self.middleware_stack(scope, receive, send)
> backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
> backend-1  |     raise exc
> backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
> backend-1  |     await self.app(scope, receive, _send)
> backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
> backend-1  |     await self.app(scope, receive, send)
> backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/sessions.py", line 77, in __call__
> backend-1  |     await self.app(scope, receive, send_wrapper)
> backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
> backend-1  |     raise exc
> backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
> backend-1  |     await self.app(scope, receive, sender)
> backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
> backend-1  |     await route.handle(scope, receive, send)
> backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
> backend-1  |     await self.app(scope, receive, send)
> backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
> backend-1  |     response = await func(request)
> backend-1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 234, in app
> backend-1  |     response_data = await serialize_response(
> backend-1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 137, in serialize_response
> backend-1  |     raise ValidationError(errors, field.type_)
> backend-1  | pydantic.error_wrappers.ValidationError: 10 validation errors for MetadataSubmissionResponse
> backend-1  | response -> results -> 0 -> metadata_submission -> studyForm -> funding_sources
> backend-1  |   field required (type=value_error.missing)
> backend-1  | response -> results -> 1 -> metadata_submission -> studyForm -> funding_sources
> backend-1  |   field required (type=value_error.missing)
> backend-1  | response -> results -> 2 -> metadata_submission -> studyForm -> funding_sources
> backend-1  |   field required (type=value_error.missing)
> backend-1  | response -> results -> 3 -> metadata_submission -> studyForm -> funding_sources
> backend-1  |   field required (type=value_error.missing)
> backend-1  | response -> results -> 4 -> metadata_submission -> studyForm -> funding_sources
> backend-1  |   field required (type=value_error.missing)
> backend-1  | response -> results -> 5 -> metadata_submission -> studyForm -> funding_sources
> backend-1  |   field required (type=value_error.missing)
> backend-1  | response -> results -> 6 -> metadata_submission -> studyForm -> funding_sources
> backend-1  |   field required (type=value_error.missing)
> backend-1  | response -> results -> 7 -> metadata_submission -> studyForm -> funding_sources
> backend-1  |   field required (type=value_error.missing)
> backend-1  | response -> results -> 8 -> metadata_submission -> studyForm -> funding_sources
> backend-1  |   field required (type=value_error.missing)
> backend-1  | response -> results -> 9 -> metadata_submission -> studyForm -> funding_sources
> backend-1  |   field required (type=value_error.missing)
> ```
> 
> I think possible paths forward are:
> 
> * Type `funding_sources` as an `Optional[str]` in StudyForm
> * Create a [new migration](https://github.com/microbiomedata/nmdc-server/blob/main/docs/development.md#generating-new-migrations) to back-populate the `funding_sources` field set to an empty string in existing submissions.

I went with the option to make funding_sources optional, which I should have done to begin with since it's an optional field. I tried making a study without funding before making that change, got the error you showed, and then updated the code and all the studies loaded as expected.

**Review by pkalita-lbl — CHANGES_REQUESTED** [review]
Sorry, one more request. There's a bit of a question around the multiplicity of funding source vs funding sources. Ultimately when this goes into MongoDB, it will go into a slot called `funding_sources` which is multivalued. With these changes only _one_ funding source can be entered -- which is all that was asked for in the issue. 

I'm not suggesting that we should expand the scope of this issue now (tagging @mslarae13 in case she wants to chime in), but I'd suggest replacing `funding_sources` with `fundingSource` in these changes to more accurately reflect what is being stored (and be consistent with the existing camel case names).

**Comment by JamesTessmer** [comment]
I've made that change, that's actually what I had named the variable to begin with but I saw it was `funding_sources` in the mongo schema. I should've trusted my first thought hah.

**Review by pkalita-lbl — APPROVED** [review]

**Comment by JamesTessmer** [comment]
@pkalita-lbl can you merge the branch? I still don't have permission to merge in this repo.

**Comment by pkalita-lbl** [comment]
Ah sorry about that! And I have permission to merge but not the permission to give you permission 😂

**Comment by JamesTessmer** [comment]
> Ah sorry about that! And I have permission to merge but not the permission to give you permission 😂

All good, who do I need to bug about getting permission for that?

**Comment by pkalita-lbl** [comment]
Probably @naglepuff or @jeffbaumes

**Comment by mslarae13** [comment]
Tested in dev and the funding box looks good to me. I wonder if we can add an example link like the Data Portal link we have with the study description box... 
link to this one https://data.microbiomedata.org/details/study/nmdc:sty-11-8fb6t785

**Comment by mslarae13** [comment]
Screenshot 2024-08-13 at 3 42 12 PM

**Comment by JamesTessmer** [comment]
I think adding a link to that study as an example should be pretty trivial to add, we can do that. If there's any changes we want to the description text we can do that as well.

**Pull request merged**
