### PR TITLE
Implement `/api/version` API endpoint that returns app version

### PR DESCRIPTION
**Pull request by eecavanna**
### Summary

- Implemented an API endpoint (`/api/version`) that returns the application version number
- Added a test targeting that endpoint
- Note: Most of the commits in this branch are related to linting

Screenshot showing that the API returns the same version number as Swagger UI shows:

image

### CODE REVIEW

**Comment by eecavanna** [comment]
Linting is failing in GitHub Actions. I don't know how I can run the same checks locally so as to avoid racking up GHA costs.

https://github.com/microbiomedata/nmdc-server/actions/runs/7480175478/job/20359024322?pr=1111#step:8:144

```py
tox: lint
  lint: commands[0]> flake8 nmdc_server tests
  nmdc_server/api.py:11: [I001] isort found an import in the wrong position
  nmdc_server/api.py:12: [I005] isort found an unexpected missing import
  nmdc_server/api.py:26: [I001] isort found an import in the wrong position
  lint: exit 1 (1.47 seconds) /home/runner/work/nmdc-server/nmdc-server> flake8 nmdc_server tests pid=3093
lint: FAIL ✖ in 3.99 seconds
```

For now, I'll look at the flake8 docs and try to map those to the code.

**Comment by naglepuff** [comment]
> Linting is failing in GitHub Actions. I don't know how I can run the same checks locally so as to avoid racking up GHA costs.

You should be able to run locally with `tox`.

If you just want to run the linting test, try `tox -e lint`.

You can also try auto-formatting the files with `tox -e format`, which will use `black` to format the python files. You can check `black`'s work by re-running `tox -e lint`.

**Comment by eecavanna** [comment]
Thanks, @naglepuff. By the way, I made another commit before I saw your message (it's being GHA tested now). 

I had been trying to run everything (including `tox`) with the Docker container, since I don't have the dependencies installed directly on my host. If the current GHA test fails, I'll try to get my host machine set up to run `tox` (and the other commands you listed)—thanks!

**Review by naglepuff — APPROVED** [review]
LGTM!

**Comment by eecavanna** [comment]
Thanks! I forgot to say: you can "squash" the branch into a single commit (upon merge, assuming GitHub still offers that ability) if you want. I consider most of the commits to have been "noise."

**Comment by eecavanna** [comment]
FYI - I don't have access to merge this.

image

Merging it is not particularly urgent, from my perspective.

**Comment by ssarrafan** [comment]
Appears to be active. Moving to new sprint. Please remove from sprint if not actively working on this.

**Pull request merged**
