### PR TITLE
Update development.md

### PR DESCRIPTION
**Pull request by shreddd**
Add current redirect URIs to docs.

### CODE REVIEW

**Review by eecavanna — APPROVED** [review]
Thanks for documenting this. Given that the list includes some non-nmdc-server URLs, I'm wondering whether this list would fit better in the `infra-admin` repo long term. Anyway, I still think it's an enhancement to the current documentation here. It can be moved to `infra-admin` later.

**Review by naglepuff — APPROVED** [review]
I agree with @eecavanna's assessment that this documentation might serve us better by being elsewhere (like the infra-admin repo) but there's no harm in having it here.

**Comment by shreddd** [comment]
OK - thanks - I agree with making a separate (and more complete) ORCID doc in the infra-admin repo. 

However, the issue of how nmdc-server uses the REDIRECT_URI in ORCID has come up a few times, and since we do have a section on ORCID auth here, I think it is useful to mention the valid URIs.

**Comment by eecavanna** [comment]
I created an issue in the `infra-admin` repo just now, for transferring this list to that repo. Here's a link to the issue: https://github.com/microbiomedata/infra-admin/issues/87

**Pull request merged**
