### PR TITLE
Search V2

### PR DESCRIPTION
**Pull request by subdavis**
See [V2 README](https://github.com/microbiomedata/nmdc-server/blob/client/v2-search/web/src/v2/README.md) for more info.

Edit: v2 == #200 nice.

### CODE REVIEW

**Comment by jeffbaumes** [comment]
@subdavis When you get a chance could you through some imgs or gifs up here so we can see how it looks at the moment? Or is there nothing to see yet and this is a code reorg at this point?

**Comment by subdavis** [comment]
@jeffbaumes how it looks is a little misleading, and so I didn't want to upload an image and have people think I'd misunderstood the goal.  It's going to be a little Frankenstein for a while as I reorganize.

Here's a screenshot, though.

Screenshot from 2021-01-26 14-37-22

**Comment by subdavis** [comment]
Bit more to look at today.  Haven't looked into jon's addition of function search features yet.

Screenshot from 2021-01-27 17-26-33

**Comment by jeffbaumes** [comment]
Looking much closer, nice! There are a couple aspects that differ from my expectation so far:

* Read QC, Metagenome Annotation, and Metagenome Assembly are all stages of the Metagenome pipeline. The idea is to group the files under a single Metagenome button, with subsections for each set of files for each part of the pipeline. This was why there was e.g. a "QC" grouping in Faiza's mockups. The mockup has the QC stage when selecting Metaproteome I believe, but really these are under Metagenome.
* The number in parentheses in the 'omics type button is the number of *pipelines* not the number of files. So in the case of your screenshot, I believe each sample has just 1 Metagenome pipeline, so there should be a single button that says "Metagenome (1)". It may make sense to only show the number when there is more than one pipeline of the same type for a sample.
* Not sure what the "(2)" after the download button means. Is that supposed to be the download count?

**Comment by subdavis** [comment]
``` json
      "omics_data": [
        {
          "id": "nmdc:cd36fb4b9995b285af511fd438e31093",
          "name": "ReadQC activiity 1778_72759",
          "type": "nmdc:ReadQCAnalysisActivity",
          "git_url": "https://github.com/microbiomedata/ReadsQC/releases/tag/1.0.0",
          "started_at_time": "2020-03-20T00:00:00",
          "ended_at_time": "2020-03-20T00:00:00",
          "execution_resource": "NERSC - Cori",
          "project_id": "gold:Gp0108340",
          "outputs": [
            {
              "id": "nmdc:07e34d7f3171788a444e87b6967e7c45",
              "name": "filterStats.txt",
              "description": "Filtered read data stats for gold:Gp0108340",
              "file_size_bytes": 286,
              "md5_checksum": null
            },
            {
              "id": "nmdc:a40b72c54245fb304adc29d5786f3039",
              "name": "1778_72759.filtered.fastq.gz",
              "description": "Filtered read data for gold:Gp0108340",
              "file_size_bytes": 3050946588,
              "md5_checksum": null
            }
          ]
        },
        {
          "id": "nmdc:aaf046ca06231f22877b2f589483909e",
          "name": "MetagenomeAnnotation activity for gold:Gp0108340",
          "type": "nmdc:MetagenomeAnnotation",
          "git_url": "https://github.com/microbiomedata/mg_annotation/releases/tag/0.1",
          "started_at_time": "2020-06-12T00:00:00",
          "ended_at_time": "2020-06-12T00:00:00",
          "execution_resource": "NERSC - Cori",
          "project_id": "gold:Gp0108340",
          "outputs": [
            {
              "id": "nmdc:ce49f5ea65c07f438a3b1f4864883223",
              "name": "gold:Gp0108340_KO TSV File",
              "description": "KO TSV File for gold:Gp0108340",
              "file_size_bytes": 116726,
              "md5_checksum": null
            },
            {
              "id": "nmdc:ba4ab38ad21931a6ee4fb5caa38cfbb3",
              "name": "gold:Gp0108340_EC TSV File",
              "description": "EC TSV File for gold:Gp0108340",
              "file_size_bytes": 82005,
              "md5_checksum": null
            },
            {
              "id": "nmdc:b71cdab4724f5045b97ea25bf95744d0",
              "name": "gold:Gp0108340_Protein FAA",
              "description": "Protein FAA for gold:Gp0108340",
              "file_size_bytes": 1069703,
              "md5_checksum": null
            },
            {
              "id": "nmdc:2f0fcf7524586b2ace092df82ae37c17",
              "name": "gold:Gp0108340_Functional annotation GFF file",
              "description": "Functional annotation GFF file for gold:Gp0108340",
              "file_size_bytes": 1241467,
              "md5_checksum": null
            },
            {
              "id": "nmdc:980737e36870cdeb97a75522c5e9e360",
              "name": "gold:Gp0108340_Structural annotation GFF file",
              "description": "Structural annotation GFF file for gold:Gp0108340",
              "file_size_bytes": 695019,
              "md5_checksum": null
            }
          ]
        },
        {
          "id": "nmdc:f21f485376cfa73f1bd68080000ffce0",
          "name": "Metagenome assembly 1778_72759",
          "type": "nmdc:MetagenomeAssembly",
          "git_url": "https://github.com/microbiomedata/metaAssembly/releases/tag/1.0.0",
          "started_at_time": "2020-03-23T00:00:00",
          "ended_at_time": "2020-03-23T00:00:00",
          "execution_resource": "NERSC - Cori",
          "project_id": "gold:Gp0108340",
          "outputs": [
            {
              "id": "nmdc:b21ea7af2398775298d67ee774f87a96",
              "name": "mapping_stats.txt",
              "description": "Metagenome Contig Coverage Stats for gold:Gp0108340",
              "file_size_bytes": 400534,
              "md5_checksum": null
            },
            {
              "id": "nmdc:378a1c482680e9d9cba54cead6b06c40",
              "name": "assembly_contigs.fna",
              "description": "Assembled contigs fasta for gold:Gp0108340",
              "file_size_bytes": 1750172,
              "md5_checksum": null
            },
            {
              "id": "nmdc:7995881b2192a243ff64f4a3eed866fb",
              "name": "assembly_scaffolds.fna",
              "description": "Assembled scaffold fasta for gold:Gp0108340",
              "file_size_bytes": 1735327,
              "md5_checksum": null
            },
            {
              "id": "nmdc:de6d668732943354ad0dddcf9c9ec47a",
              "name": "assembly.agp",
              "description": "Assembled AGP file for gold:Gp0108340",
              "file_size_bytes": 299265,
              "md5_checksum": null
            },
            {
              "id": "nmdc:8ca338389d2d6b1c8d47c1f0c2c48e31",
              "name": "pairedMapped_sorted.bam",
              "description": "Metagenome Alignment BAM file for gold:Gp0108340",
              "file_size_bytes": 3446893950,
              "md5_checksum": null
            }
          ]
        }
      ]
```

Here's the data I'm working from.  I made assumptions about how this aligns with the mockup that I guess were wrong.  Could you help me clarify some things.

* I assumed there was missing data in the rows (outputs above) that distinguished these as spread between pipeline runs
* Is each `omics_data` object a pipeline run?  Is each `omics_data` a stage?
* I don't see anything in the mockup about how to distinguish between stages in the resulting data table. Is each data object the result of a stage?  Is each grouping of data objects a stage?  If so, then the converse: I don't see anything about how to distinguish pipeline runs.
* Specifically
  * What is the "stage" key in the object above?
  * What is the pipeline run key?
  * I don't have anything that looks like the first column of the mockup table as the "pipeline stage name".  I have `"MetagenomeAnnotation activity for gold:Gp0108335"`, but that may or may not be the desired item to put there.

> * Read QC, Metagenome Annotation, and Metagenome Assembly are all stages of the Metagenome pipeline. The idea is to group the files under a single Metagenome button, with subsections for each set of files for each part of the pipeline. This was why there was e.g. a "QC" grouping in Faiza's mockups. The mockup has the QC stage when selecting Metaproteome I believe, but really these are under Metagenome.

Could someone point to the desired mappings of `omics_data[].type` to group? 

Also, @jbeezley is this your understanding as well?   Mostly just verifying that you haven't twisted the data to conform to what I asked for only to have me twist it back in the other direction given the above.

> The number in parentheses in the 'omics type button is the number of pipelines not the number of files. So in the case of your screenshot, I believe each sample has just 1 Metagenome pipeline, so there should be a single button that says "Metagenome (1)". It may make sense to only show the number when there is more than one pipeline of the same type for a sample.

I figured there just wasn't enough info to derive the "right" number yet.

> Not sure what the "(2)" after the download button means. Is that supposed to be the download count?

Yes, but I didn't put much thought into it.   Just something to signal "we can do this".  Suggestions welcome.

**Comment by jbeezley** [comment]
Maybe we should meet about this, but this is my understanding.

A pipeline run is a project, which as of now is 1-1 with a biosample.  The `omics_data` objects in the response are all workflow execution activities (steps in the pipeline).  They all have a list of output files (or data_objects) which are listed as "outputs".

Besides grouping metagenome related activities together, I don't think there is any other relevant relationships.  So from the screenshot the top level rows are biosamples, then the buttons are showing the different workflow execution activities (either `omics_data` objects or groups of them as noted).  Then the rows under that are outputs from those activities.

**Comment by subdavis** [comment]
Screenshot from 2021-01-28 10-02-52

So metabolomics, proteomics, and OMC are different pipeline runs.

But the data in `omics_data`  corresponds to stages, and to get pipeline runs, we need to group them using some mapping.

> Besides grouping metagenome related activities together, I don't think there is any other relevant relationships.

Cool.

So all I really need is a pointer to the formal mapping between an enum of the buttons and `omics_data[].type` so I can group them.

**Comment by jeffbaumes** [comment]
I think you want to group by `omics_data[].project_id` to find what pipeline (i.e. `project`) the stage is part of. To know what type the project is (e.g. "Metagenomics"), you would look in the `project.annotations.omics_type` field of the project record.

In general, there could be multiple projects (i.e. pipelines) of a certain `omics_type`, which is the reason for two major groupings in the "Omics" column in the mockup. The `id`, `name`, or `description` of the `project` object could be displayed here, we'd want feedback from the team on that. 

Also, my understanding is that you'd populate the "Data Object Type" column with the pipeline stage the data object came from for now from `omics_data[].type` (e.g. where the mockup has "QC" you would put "nmdc:ReadQCAnalysisActivity", maybe exclude the "nmdc:" for display).

**Comment by dehays** [comment]
@subdavis We can clarify further at 2pm.  Reading the above - I think there is a little different term usage than what I am familiar with.  (Jon indicated that a 'pipeline run is a project' - usually pipeline and workflow are used to describe some defined analysis done by software tools.  A project (what is in Jon's project table, what is in the NMDC schema as on omics_processing) refers to a thing done by a machine (a sequencer, a mass spec instrument) with a physical sample as input and data as output.  What I see in the 'omics_data' array above are analysis execution activities of different types (ReadQC, MetaG Assembly, MetaG Annotation) with the output dataobject inlined (and no URL properties?).  

I think what you are getting at is the fact that for metagenome sequencing, after ReadQC takes the sequencer produced raw reads as input, the output of one type of analysis activity (pipeline, workflow) becomes the input of another.   I think the grouping you are looking is found by the project_id in Jon's omics_data objects.  That is a reference from each analysis activity to the instrument process was originally applied to a sample.  So all the metagenome related analysis activities (Jon's omics_data objects) would refer to the same project_id, the ID of the same metagenome sequencing.

**Comment by jeffbaumes** [comment]
Thanks @dehays I think we are pretty much in unison here, and we'll hopefully further clarify at the standup.

**Comment by jbeezley** [comment]
There is definitely confusion surrounding domain object names, some of which I made up.  Much of it is too ingrained in the code to change in the current sprint.

For reference:
* project == omics processing
* pipeline == workflow execution activity
* workflow execution activity is a generic type of read qc, metagenome annotation, etc.

It sounds like I could break out the output into another hierarchy level:
```
biosample -> project -> workflow activity -> data object
```
If all you need to do is group by project id, then what is there is sufficient.  However, if you need something like the project name, then it would be best to make the change server side.

**Comment by jeffbaumes** [comment]
@jbeezley thanks for the clarification. I'd been using
* omics processing == project == "pipeline"
* workflow execution activity == "pipeline stage"

But I suggest we move to your definitions.

> It sounds like I could break out the output into another hierarchy level:
> biosample -> project -> workflow activity -> data object

Yes, adding another level server side for project which includes at minimum `id`, `name`, `description`, `annotations.omics_type` would be helpful and clarifying.

**Comment by dehays** [comment]
This might help - this is a diagram I did for one of the reviews showing the relationship between entities in the schema with a concrete case.  It shows the line of analysis downstream from metaG sequencing and from a metaP instrument run with the connections between outputs and inputs:

image

**Comment by subdavis** [comment]
Update (just for biosample, nothing else changed)

Still working within the confines of what a `v-data-table` is capable of.  If we end up having to ditch it, we can, but I'm not going to prioritize strict mockup adherence until things are further along.

Screenshot from 2021-01-28 17-22-24

**Comment by subdavis** [comment]
Here's where I ended up today.

* Got a little more "stuff" populated in the sidebar to demonstrate facets from every category all available on the same page.
* Study checkbox search refinement works.
* Jon fixed data coming back for workflow activities.

Not complete by any means, but hopefully this gets the idea across.

Screenshot from 2021-01-29 17-19-39
Screenshot from 2021-01-29 17-19-23
Screenshot from 2021-01-29 17-18-49
Screenshot from 2021-01-29 17-18-37

**Comment by jeffbaumes** [comment]
Nice! A few suggestions as you continue to work on this:

* Show the study name instead of the study ID under the sample
* Make the samples area outline look like the other group outlines (i.e. thin line without shadow)
* I'd remove the made up download count for now. Jared had the idea of making a Download Count column in his [mockup](https://www.figma.com/file/feBjM60KV67XDXNxlgXde9/PI-Page?node-id=0%3A1), which we might try when we are actually tracking the download numbers on the server
* I think it would be slightly better to top-align the sample icon so it is always to the left of the sample name and study name, no matter if a sample's omics data is expanded or collapsed

**Comment by subdavis** [comment]
> Show the study name instead of the study ID under the sample

This is not available through the API, so would require a backend change. I might be able to do it.

> I think it would be slightly better to top-align the sample icon so it is always to the left of the sample name and study name, no matter if a sample's omics data is expanded or collapsed

I don't think I can do that with the vuetify API, but I'll see if a hack is easy.

The other two are trivial.

**Comment by jeffbaumes** [comment]
> > Show the study name instead of the study ID under the sample

> This is not available through the API, so would require a backend change. I might be able to do it.

I agree the ideal is to get it from the samples API call directly. But since the study info is already being queried to populate the study table above samples, it seems there would also be a way without modifying the server if needed.

**Comment by subdavis** [comment]
Screenshot from 2021-02-02 13-50-25

Screenshot from 2021-02-02 13-59-32

Function search and this branch will be merged and deployed soon.  Fighting with a few small bugs.

**Comment by jeffbaumes** [comment]
Looks great, a couple nits:

* Lowercase "t" in "KO term" to match the use of sentence case in the rest of the UI
* Hide the "KEGG.ORTHOLOGY:" prefix in all parts of the UI so it just says "K06207". Prepend the prefix when making the search API request.

**Comment by subdavis** [comment]
> Hide the "KEGG.ORTHOLOGY:" prefix in all parts of the UI so it just says "K06207". Prepend the prefix when making the search API request.

I wasn't sure if there were other prefixes the user might need to control.  I'll remove all references to that prefix, thanks.

**Comment by jeffbaumes** [comment]
> I wasn't sure if there were other prefixes the user might need to control. I'll remove all references to that prefix, thanks.

There likely will be, but in the UI I expect we will add additional search options under "KO term" to add them to the search and prepend a different prefix for each one.

**Comment by subdavis** [comment]
Screenshot from 2021-02-02 16-30-19

This is what I've deployed.

* You can input KO term without the prefix, but it still shows up as `KEGG:ORTHOLOGY` because I wasn't able to come up with a quick way to change that app-wide.   I'll have to add some facet-specific transforms, but I didn't want my fiddling around with that to hold things up.
* I quickly threw in the omics counts for the studies.  We don't have mockups for this.  I expect they will change, I just wanted to show they were there.
* Studies are hardcoded right now while query performance is adjusted.  I think I picked the correct 3.
* Study name still not in sample list subtitle.  This will need backend support,a client side join will be messy.

There are other known bugs.

**Pull request merged**
