### PR TITLE
Fix multi-tiered search

### LINKED ISSUE #1072: KEGG search results should only display products from which the KEGG hit comes from
**Is your feature request related to a problem? Please describe.**
When searching by a KEGG search term it should only products where it makes sense to have KEGG results (metagenome, metatranscriptome, and proteomics) 
Example (https://data-dev.microbiomedata.org/?q=Ch8IABAAGAEiFyJLRUdHLk9SVEhPTE9HWTpLMDAwMDki)

**Describe the solution you'd like**
A metagenome sample has a hit to the KEGG term and also has a metatranscriptome with no KEGG hit and metabolomics the sample results should only show the metagenome product. The count of metagenomes at the study level should be the number of metagenomes in that study that have the KEGG term, not the total number of metagenome projects in the entire study. 
Minimum requirement for GSP would be to hid metabolomics and natural organic matter results for studies and samples

**Describe alternatives you've considered**
Minimum requirement for GSP would be to hid metabolomics and natural organic matter results for studies and samples

**Acceptance Criteria**
Search by KEGG term  shows the number of projects within a study that have hits and only those with products. At the sample level only show products with the KEGG hit.
Screenshot 2023-03-30 at 7 47 23 PM

### PR DESCRIPTION
**Pull request by naglepuff**
Fix #1072 

The NMDC Data Portal allows adding filters on multiple properties across different levels of the NMDC schema hierarchy. For example, one can add a search filter at the biosample level (depth) and see results from the study and data object level.

Prior to this change, searching across multiple hierarchies could introduce some unexpected results due to how our queries were being constructed. Examples of this inconsistency are documented fairly well in #1072 and #1085.

The fix for #1085 was the first step toward fixing this larger problem, which this PR aims to expand to be a fully fledged fix.

### CODE REVIEW

**Comment by naglepuff** [comment]
Borrowing a [screenshot](https://github.com/microbiomedata/nmdc-server/issues/1072#issuecomment-1791604544) from #1072:
image

There is a study and biosamples showing up in the results that should not be. This is because both of the active search terms use `omics_processing` records as the basis for search. Since building the SQL queries works from the top down, the queries for `biosample` and `study` effectively "or" these conditions together since they are lower on the `study -> sample -> omics` hierarchy.

The change in this PR will "pre-filter" records that are lower on the hierarchy, to avoid the pseudo-or behavior previously seen. In my local environment, the search above yields:
image

**Comment by naglepuff** [comment]
@aclum besides the query mentioned above from #1072, are there any other specific sets of filters that you've noticed with unexpected results?

**Comment by jeffbaumes** [comment]
@naglepuff at a brief glance the logic looks sound. Study search needs to "chain down" to sample (done in the previous fix) and omics processsing, and sample search needs to "chain down" to omics processing.

**Review by jeffbaumes — COMMENTED** [review]
I'm retroactively approving :) Looks good.

**Pull request merged**
